"""
Minimal Tkinter GUI wrapper for the new pipeline.

This keeps the legacy CLI intact while providing a simple point-and-click
entrypoint that runs `coastsat_pipeline.cli.run_pipeline_from_config`.
"""

from __future__ import annotations

import logging
import threading
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

from .cli import run_pipeline_from_config


class _TextHandler(logging.Handler):
    """
    Logging handler that appends log messages to a Tkinter Text widget.
    """

    def __init__(self, text_widget: tk.Text):
        super().__init__()
        self.text_widget = text_widget
        self.text_widget.configure(state="disabled")

    def emit(self, record: logging.LogRecord) -> None:
        msg = self.format(record)
        # Use .after to marshal UI updates back to the Tk thread.
        self.text_widget.after(0, self._append, msg)

    def _append(self, msg: str) -> None:
        self.text_widget.configure(state="normal")
        self.text_widget.insert(tk.END, msg + "\n")
        self.text_widget.see(tk.END)
        self.text_widget.configure(state="disabled")


class PipelineGUI:
    """
    Thin desktop shell to run the refactored pipeline from a settings.json.
    """

    def __init__(self) -> None:
        self.root = tk.Tk()
        self.root.title("CoastSat Pipeline")
        self.root.geometry("640x420")

        self.config_path_var = tk.StringVar()
        self.status_var = tk.StringVar(value="Select a settings.json generated by the CLI and click Run.")
        self._worker: threading.Thread | None = None

        self._build_layout()
        self._configure_logging()

    def _build_layout(self) -> None:
        main = ttk.Frame(self.root, padding=12)
        main.pack(fill=tk.BOTH, expand=True)

        # Config row
        cfg_label = ttk.Label(main, text="Config path (settings.json):")
        cfg_label.grid(row=0, column=0, sticky="w")

        cfg_entry = ttk.Entry(main, textvariable=self.config_path_var)
        cfg_entry.grid(row=1, column=0, columnspan=2, sticky="we", pady=(0, 8))

        browse_btn = ttk.Button(main, text="Browse...", command=self._pick_config)
        browse_btn.grid(row=1, column=2, padx=(8, 0), sticky="we")

        # Run controls
        self.run_btn = ttk.Button(main, text="Run Pipeline", command=self._on_run_clicked)
        self.run_btn.grid(row=2, column=0, sticky="w")

        self.status_label = ttk.Label(main, textvariable=self.status_var, foreground="#333")
        self.status_label.grid(row=2, column=1, columnspan=2, sticky="w")

        # Log area
        log_label = ttk.Label(main, text="Logs:")
        log_label.grid(row=3, column=0, sticky="w", pady=(12, 0))

        self.log_text = tk.Text(main, wrap="word", height=16)
        self.log_text.grid(row=4, column=0, columnspan=3, sticky="nsew")

        log_scroll = ttk.Scrollbar(main, command=self.log_text.yview)
        log_scroll.grid(row=4, column=3, sticky="ns")
        self.log_text.configure(yscrollcommand=log_scroll.set)

        main.columnconfigure(0, weight=1)
        main.columnconfigure(1, weight=1)
        main.columnconfigure(2, weight=0)
        main.rowconfigure(4, weight=1)

    def _configure_logging(self) -> None:
        # Ensure INFO-level messages surface in the UI.
        formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", "%H:%M:%S")
        handler = _TextHandler(self.log_text)
        handler.setFormatter(formatter)

        root_logger = logging.getLogger()
        root_logger.setLevel(logging.INFO)
        root_logger.addHandler(handler)

    def _pick_config(self) -> None:
        initial_dir = Path(self.config_path_var.get()).expanduser().parent if self.config_path_var.get() else Path.cwd()
        path = filedialog.askopenfilename(
            title="Select settings.json",
            filetypes=(("JSON files", "*.json"), ("All files", "*.*")),
            initialdir=initial_dir,
        )
        if path:
            self.config_path_var.set(path)

    def _on_run_clicked(self) -> None:
        config_path = Path(self.config_path_var.get()).expanduser()
        if not config_path.exists():
            messagebox.showerror("Missing config", f"Config not found: {config_path}")
            return

        if self._worker and self._worker.is_alive():
            messagebox.showinfo("Pipeline running", "A pipeline run is already in progress.")
            return

        self.status_var.set("Running...")
        self.run_btn.configure(state="disabled")

        self._worker = threading.Thread(target=self._run_pipeline, args=(config_path,), daemon=True)
        self._worker.start()

    def _run_pipeline(self, config_path: Path) -> None:
        logger = logging.getLogger(__name__)
        logger.info("Starting pipeline with config: %s", config_path)
        try:
            run_pipeline_from_config(config_path)
        except Exception as exc:  # noqa: BLE001
            logging.getLogger().exception("Pipeline failed: %s", exc)
            self.root.after(0, self._on_finished, False, str(exc))
        else:
            self.root.after(0, self._on_finished, True, "")

    def _on_finished(self, success: bool, error_msg: str) -> None:
        if success:
            self.status_var.set("Completed successfully.")
            messagebox.showinfo("Done", "Pipeline completed successfully.")
        else:
            self.status_var.set("Failed. Check logs.")
            messagebox.showerror("Pipeline failed", f"Pipeline run failed:\n{error_msg}")

        self.run_btn.configure(state="normal")

    def run(self) -> None:
        self.root.mainloop()


def main() -> None:
    PipelineGUI().run()


if __name__ == "__main__":
    main()
